services:
  - type: web
    name: epilogo-backend
    env: docker
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: JWT_REFRESH_EXPIRATION
        value: 604800000
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: epilogo-db
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: epilogo-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: epilogo-db
          property: password

databases:
  - name: epilogo-db
    plan: free